# Generated by Django 5.2.16 on 2026-07-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id_sugestao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sugestao', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=300)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('data_sugestao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sugestao',
                'managed': False,
            },
        ),
    ]
