# Generated by Django 6.0.6 on 2026-06-25 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponto_turistico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id_sugestao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sugestao', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=300)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('data_sugestao', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='ponto_turistico.categoria')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SUGESTAO',
            },
        ),
    ]
