# Generated by Django 6.0.6 on 2026-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_categoria', primary_key=True, serialize=False)),
                ('descricao_categoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'CATEGORIAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_usuario', primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=45)),
                ('senha', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sugestao',
            options={'managed': False},
        ),
    ]
