# Generated by Django 5.2.17 on 2026-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sugestoes/'),
        ),
    ]
