# Generated by Django 6.0.6 on 2026-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='ID_perfil', primary_key=True, serialize=False)),
                ('descricao_perfil', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'PERFIL',
            },
        ),
    ]
