# Generated by Django 6.0.6 on 2026-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nome_categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao_categoria',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(db_column='ID_categoria', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='CATEGORIA',
        ),
    ]
