# Generated by Django 5.2.15 on 2026-06-23 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponto_turistico', '0002_alter_pontoturistico_options_pontoturistico_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='ponto_turistico.pontoturistico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='favorito_fa_usuario_95dad0_idx'), models.Index(fields=['ponto_turistico'], name='favorito_fa_ponto_t_29d62f_idx')],
                'unique_together': {('usuario', 'ponto_turistico')},
            },
        ),
    ]
