# Generated by Django 6.0.6 on 2026-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(db_column='nome_usuario', max_length=75)),
                ('email', models.EmailField(db_column='email', max_length=191, unique=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='data_nascimento', null=True)),
                ('foto_perfil', models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='perfis/')),
                ('password', models.CharField(db_column='senha', max_length=128)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(db_column='id_avaliacao', primary_key=True, serialize=False)),
                ('estrela', models.IntegerField(db_column='estrela')),
                ('mensagem', models.TextField(blank=True, db_column='mensagem', null=True)),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(db_column='id_favorito', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='id_perfil', primary_key=True, serialize=False)),
                ('descricao_perfil', models.CharField(db_column='descricao_perfil', max_length=45)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
    ]
