# Generated by Django 5.2.16 on 2026-07-22 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='id_perfil', primary_key=True, serialize=False)),
                ('descricao_perfil', models.CharField(db_column='descricao_perfil', max_length=45)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(db_column='nome_usuario', max_length=75)),
                ('email', models.EmailField(db_column='email', max_length=100, unique=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='data_nascimento', null=True)),
                ('foto_perfil', models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='perfis/')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Indica se este usuário deve ser tratado como ativo.')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, help_text='Indica se o usuário pode acessar o admin site.')),
                ('date_joined', models.DateTimeField(db_column='date_joined', default=django.utils.timezone.now, help_text='Data de registro do usuário.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, to='usuario.perfil')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
