# Generated by Django 6.0.6 on 2026-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_column='data_cadastro')),
                ('perfil_id', models.IntegerField(db_column='PERFIL_ID_perfil')),
                ('password', models.CharField(db_column='senha', max_length=128)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
