# Generated by Django 5.2.16 on 2026-07-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='id_perfil', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.perfil'),
        ),
    ]
