# Generated by Django 6.0.6 on 2026-06-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_cadastro',
        ),
    ]
