# Generated by Django 5.2.15 on 2026-06-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_cadastro',
        ),
    ]
