# Generated by Django 6.0.6 on 2026-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='ID_usuario', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIO',
        ),
    ]
