# Generated by Django 6.0.6 on 2026-06-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(db_column='id_avaliacao', primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, db_column='comentario', null=True)),
                ('nota', models.IntegerField(db_column='nota')),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(db_column='id_favorito', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='id_perfil', primary_key=True, serialize=False)),
                ('descricao_perfil', models.CharField(db_column='descricao_perfil', max_length=45)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='senha', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_perfil',
            field=models.ForeignKey(db_column='id_perfil', default=2, on_delete=django.db.models.deletion.PROTECT, to='usuario.perfil'),
        ),
    ]
