# Generated by Django 6.0.6 on 2026-07-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id_ponto_turistico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ponto_turistico', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField()),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(default='Belém', max_length=100)),
                ('imagem_url', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ponto_turistico',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_categoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_ponto_turistico', models.ForeignKey(db_column='id_ponto_turistico', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ponto_avaliacoes_set', serialize=False, to='ponto_turistico.pontoturistico')),
                ('mensagem', models.TextField()),
                ('estrela', models.IntegerField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_ponto_turistico', models.ForeignKey(db_column='id_ponto_turistico', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ponto_favoritos_set', serialize=False, to='ponto_turistico.pontoturistico')),
                ('data_favorito', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorito',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, to='ponto_turistico.categoria'),
        ),
    ]
