# Generated by Django 5.2.15 on 2026-06-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id_ponto_turistico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ponto_turistico', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
    ]
