# Generated by Django 5.2.16 on 2026-07-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('estrela', models.IntegerField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_categoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_favorito', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorito',
            },
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id_ponto_turistico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ponto_turistico', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField()),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(default='Belém', max_length=100)),
                ('imagem_url', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ponto_turistico',
            },
        ),
    ]
