# Generated by Django 6.0.6 on 2026-07-07 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_turistico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='id_ponto_turistico',
            field=models.ForeignKey(db_column='id_ponto_turistico', on_delete=django.db.models.deletion.CASCADE, related_name='ponto_avaliacoes_set', to='ponto_turistico.pontoturistico'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usuario_avaliacoes_ponto_set', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
