# Generated by Django 5.2.15 on 2026-06-25 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponto_turistico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorito',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, to='ponto_turistico.categoria'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='id_ponto_turistico',
            field=models.ForeignKey(db_column='id_ponto_turistico', on_delete=django.db.models.deletion.CASCADE, to='ponto_turistico.pontoturistico'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='id_ponto_turistico',
            field=models.ForeignKey(db_column='id_ponto_turistico', on_delete=django.db.models.deletion.CASCADE, to='ponto_turistico.pontoturistico'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('id_usuario', 'id_ponto_turistico')},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('id_usuario', 'id_ponto_turistico')},
        ),
    ]
