# Generated by Django 5.2.15 on 2026-06-23 23:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_options_categoria_ativo_and_more'),
        ('ponto_turistico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Ponto Turístico', 'verbose_name_plural': 'Pontos Turísticos'},
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada GPS - Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada GPS - Longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='media_avaliacoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='total_avaliacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='nome_ponto_turistico',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='pontoturistico',
            index=models.Index(fields=['cidade'], name='ponto_turis_cidade_303948_idx'),
        ),
        migrations.AddIndex(
            model_name='pontoturistico',
            index=models.Index(fields=['categoria'], name='ponto_turis_categor_332134_idx'),
        ),
        migrations.AddIndex(
            model_name='pontoturistico',
            index=models.Index(fields=['-media_avaliacoes'], name='ponto_turis_media_a_f92e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='pontoturistico',
            index=models.Index(fields=['latitude', 'longitude'], name='ponto_turis_latitud_83f1b8_idx'),
        ),
    ]
