# Generated by Django 6.0.6 on 2026-06-27 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_turistico', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='id_ponto_turistico',
            field=models.ForeignKey(db_column='id_ponto_turistico', on_delete=django.db.models.deletion.CASCADE, related_name='ponto_avaliados', to='ponto_turistico.pontoturistico'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='ponto_avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_ponto_turistico',
            field=models.ForeignKey(db_column='id_ponto_turistico', on_delete=django.db.models.deletion.CASCADE, related_name='ponto_favoritados', to='ponto_turistico.pontoturistico'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='ponto_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
