# Generated by Django 5.2.15 on 2026-06-23 23:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponto_turistico', '0002_alter_pontoturistico_options_pontoturistico_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='ponto_turistico.pontoturistico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['ponto_turistico', '-criado_em'], name='avaliacao_a_ponto_t_ee8f68_idx'), models.Index(fields=['usuario'], name='avaliacao_a_usuario_6d6bf1_idx')],
                'unique_together': {('usuario', 'ponto_turistico')},
            },
        ),
    ]
