# Generated by Django 6.0.6 on 2026-06-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponto_turistico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=300)),
                ('estrela', models.IntegerField()),
                ('ponto_turistico', models.ForeignKey(db_column='PONTO_TURISTICO_ID_ponto_turistico', on_delete=django.db.models.deletion.DO_NOTHING, to='ponto_turistico.pontoturistico')),
                ('usuario', models.ForeignKey(db_column='USUARIO_ID_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'AVALIACAO',
                'unique_together': {('ponto_turistico', 'usuario')},
            },
        ),
    ]
